version: '3.9'

services:
  web:
    build: .
    container_name: cinema-web
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: cinema_db
    command: [ --auth, --bind_ip_all ]

volumes:
  mongo_data:
    driver: local